CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT, admin BOOLEAN);
CREATE TABLE restaurants (id SERIAL PRIMARY KEY, owner_id INTEGER REFERENCES users, name TEXT UNIQUE, adress TEXT, city TEXT);
CREATE TABLE r_stars (id SERIAL PRIMARY KEY, r_id INTEGER REFERENCES users, rating INTEGER);
CREATE TABLE r_quetimes (id SERIAL PRIMARY KEY, r_id INTEGER REFERENCES users, que_time INTEGER);
